# Generated by Django 2.2.12 on 2023-03-29 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follower',
            name='time',
        ),
        migrations.AlterField(
            model_name='follower',
            name='date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Follower_date'),
        ),
        migrations.AlterField(
            model_name='follower_date',
            name='time',
            field=models.TimeField(),
        ),
    ]
